services:
  - type: web
    name: agriscan-boat
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_KEY
        generateValue: true
      - key: LINE_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
      - key: OFFLINE_ALERT_MIN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: agriscan-db
          property: connectionString

databases:
  - name: agriscan-db
    plan: free
    databaseName: agriscan
    user: agriscan
